# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.network "private_network", ip: "192.168.33.33"

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "../src", "/var/www/html", :mount_options => ["dmode=777,fmode=777"]

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.provisioning_path = "/vagrant/ansible/"
  end

  # vagrantのversionによってはeth1が設定されずip設定が反映されない場合があるようなので念のためnetworkを再起動
  config.vm.provision "shell", run: "always", inline: "systemctl restart network.service"
end
